# Generated by Django 3.2.6 on 2021-08-17 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vtx', '0002_auto_20210816_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='port',
            field=models.CharField(default='COM4', max_length=20, verbose_name='porta'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('descricao', models.CharField(default='generico', max_length=50, verbose_name='Evento')),
                ('tipo', models.CharField(default='Evento', max_length=50, verbose_name='tipo de Evento')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtx.node')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
